name: Bump version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    environment: dev

    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: echo versions
        run: |
          echo "::notice title=Version::${{ steps.tag.outputs.new_version }}"
          echo "::notice title=Tag::${{ steps.tag.outputs.new_tag }}"
